app.name: web-app

server:
  port: 8081
  servlet:
    context-path: /web/

spring:
  application:
    name: web-app-service
  profiles:
    active: dev

keycloak:
  realm: my-hero-college
  auth-server-url: http://keycloak:8080/auth
  public-client: true
#  keycloak.ssl-required: external
  credentials.secret: b3ed20e9-2439-4d08-9c48-b7bbd19c8344
  resource: web-app
  use-resource-role-mappings: true
  security-constraints[0]:
    authRoles[0]: students
    securityColl0ections[0]:
      patterns[0]: /students/*


logging:
  level:
    root: debug

---
spring:
  profiles: dev